name: GitHub Script v6.1.0
on:
  issues:
    types:
      - labeled

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        router:
          - dest_repo:dest_repo
    steps:
      - uses: actions/checkout@v3
      - name: Transfer Issue & Comment
        uses: lando/transfer-issue-action@v2.0.3
        id: transfer-issue
        with:
          token: ${{ secrets.MOVE }}
          # make a variable for src repo in string bellow 
          apply_label: "Transferred from src_repo:009BBE"
          router: ${{ matrix.router}}
          debug: true
      - name: Echo Output Data
        run: |
          echo "DESTINATION REPO: ${{steps.transfer-issue.outputs.destination_repo}}"
          echo "NEW ISSUE NUMBER: ${{steps.transfer-issue.outputs.new_issue_number}}"
          echo "NEW ISSUE URL: ${{steps.transfer-issue.outputs.new_issue_url}}"
      - name: Update Transferred Issue
        uses: actions/github-script@v6.1.0
        if: steps.transfer-issue.outputs.new_issue_number != ''
        with:
          github-token: ${{ secrets.MOVE }}
          script: |
            await github.rest.issues.createComment({
              issue_number: `${{ steps.transfer-issue.outputs.new_issue_number}}`,
              owner: context.repo.owner,
              repo: `${{ steps.transfer-issue.outputs.destination_repo }}`,
              body: `@${ context.payload.issue.user.login } your issue is over here now as it belongs to this repo!`
            });